package com.example.demo.entity;

import com.example.demo.enums.PaymentStatus;
import com.example.demo.enums.TriggeredBy;
import jakarta.persistence.*;
import java.time.Instant;

/**
 * JPA Entity representing a single state transition event in the payment audit history.
 *
 * <p><b>Table Name:</b> {@code payment_status_history}</p>
 * <p><b>Responsibility:</b> Immutably record all state transitions of a payment for compliance and debugging.
 * Each history record is created once and never modified or deleted, following the audit log principle.</p>
 *
 * <p><b>Key Constraints:</b></p>
 * <ul>
 *   <li>ID is a UUID string (independent primary key, not auto-increment)</li>
 *   <li>paymentId is a foreign key pointing to payments{@code .id}</li>
 *   <li>fromStatus is null only for the initial creation record (CREATED state with no prior state)</li>
 *   <li>changedAt is indexed with paymentId for efficient history retrieval in time order</li>
 *   <li>triggeredBy distinguishes between user actions and system operations</li>
 *   <li>errorCode and notes are populated only on failure transitions</li>
 *   <li>Time is always UTC (DATETIME or TIMESTAMP column type)</li>
 * </ul>
 *
 * <p><b>Immutability:</b> This entity intentionally does not provide setters. Once created, history records
 * should not be modified. Construct via constructor or builder pattern, persist once, then only read.</p>
 *
 * <p><b>Relationship:</b> Many-to-one relationship with Payment via paymentId.
 * Payment deletion may cascade or restrict based on database configuration; iteration 1 assumes no deletion.</p>
 */
@Entity
@Table(name = "payment_status_history", indexes = {
        @Index(name = "idx_payment_id", columnList = "payment_id"),
        @Index(name = "idx_payment_changed_at", columnList = "payment_id,changed_at")
})
public class PaymentStatusHistory {

    /**
     * Unique history record identifier (UUID string).
     * Generated by application; each transition event gets its own unique ID.
     */
    @Id
    @Column(name = "id", length = 36, nullable = false)
    private String id;

    /**
     * Foreign key reference to the associated payment.
     * Links this history record to a specific Payment entity.
     * Indexed for efficient "find all history for payment X" queries.
     */
    @Column(name = "payment_id", length = 36, nullable = false)
    private String paymentId;

    /**
     * The status before this transition.
     * Null only for the initial creation record (when payment enters CREATED state).
     * All subsequent records have a non-null fromStatus.
     */
    @Column(name = "from_status", length = 20)
    @Enumerated(EnumType.STRING)
    private PaymentStatus fromStatus;

    /**
     * The status after this transition (the target state).
     * Always non-null; represents the payment status at changedAt time.
     */
    @Column(name = "to_status", length = 20, nullable = false)
    @Enumerated(EnumType.STRING)
    private PaymentStatus toStatus;

    /**
     * Indicates who triggered this state transition.
     * Values: USER (user-initiated action), SYSTEM (internal logic).
     * Used to distinguish between direct user interaction and automated operations.
     */
    @Column(name = "triggered_by", length = 50, nullable = false)
    @Enumerated(EnumType.STRING)
    private TriggeredBy triggeredBy;

    /**
     * Error code when this transition is to FAILED state.
     * Null for successful transitions; non-null for failure transitions.
     * Examples: "NETWORK_ERROR", "PROCESSING_ERROR", "INVALID_AMOUNT".
     */
    @Column(name = "error_code", length = 50)
    private String errorCode;

    /**
     * Descriptive notes about this transition.
     * For success transitions: brief explanation (e.g., "Payment sent successfully").
     * For failure transitions: actionable error details and debugging context.
     * Max 255 characters; should not contain sensitive PII or full stack traces.
     */
    @Column(name = "notes", length = 255)
    private String notes;

    /**
     * Timestamp when this state transition occurred (UTC).
     * Stored as DATETIME or TIMESTAMP; always in UTC timezone.
     * Used for chronological ordering and audit trail reconstruction.
     */
    @Column(name = "changed_at", nullable = false)
    private Instant changedAt;

    // ==================== Constructors ====================

    /**
     * No-argument constructor required by JPA.
     */
    public PaymentStatusHistory() {
    }

    /**
     * Full constructor for creating a payment status history record.
     *
     * @param id unique identifier for this history record
     * @param paymentId foreign key to the associated payment
     * @param fromStatus the status before transition (null for initial creation)
     * @param toStatus the status after transition
     * @param triggeredBy who triggered this transition (USER or SYSTEM)
     * @param errorCode error code if this is a failure transition
     * @param notes descriptive notes about the transition
     * @param changedAt when this transition occurred
     */
    public PaymentStatusHistory(String id, String paymentId, PaymentStatus fromStatus, PaymentStatus toStatus,
                                TriggeredBy triggeredBy, String errorCode, String notes, Instant changedAt) {
        this.id = id;
        this.paymentId = paymentId;
        this.fromStatus = fromStatus;
        this.toStatus = toStatus;
        this.triggeredBy = triggeredBy;
        this.errorCode = errorCode;
        this.notes = notes;
        this.changedAt = changedAt;
    }

    // ==================== Getters (Immutable Pattern) ====================

    public String getId() {
        return id;
    }

    public String getPaymentId() {
        return paymentId;
    }

    public PaymentStatus getFromStatus() {
        return fromStatus;
    }

    public PaymentStatus getToStatus() {
        return toStatus;
    }

    public TriggeredBy getTriggeredBy() {
        return triggeredBy;
    }

    public String getErrorCode() {
        return errorCode;
    }

    public String getNotes() {
        return notes;
    }

    public Instant getChangedAt() {
        return changedAt;
    }

    // ==================== Utility Methods ====================

    @Override
    public String toString() {
        return "PaymentStatusHistory{" +
                "id='" + id + '\'' +
                ", paymentId='" + paymentId + '\'' +
                ", fromStatus=" + fromStatus +
                ", toStatus=" + toStatus +
                ", triggeredBy=" + triggeredBy +
                ", changedAt=" + changedAt +
                '}';
    }
}

