package com.example.demo.entity;

import com.example.demo.enums.PaymentStatus;
import jakarta.persistence.*;
import java.math.BigDecimal;
import java.time.Instant;

/**
 * JPA Entity representing a payment record in the database.
 *
 * <p><b>Table Name:</b> {@code payments}</p>
 * <p><b>Responsibility:</b> Maintain payment data consistency and provide read/write access to persistent fields.
 * State transitions must be validated through {@code PaymentStateMachine} before calling {@code changeStatus()}.
 * Historical context is maintained separately in {@code PaymentStatusHistory}.</p>
 *
 * <p><b>Key Constraints:</b></p>
 * <ul>
 *   <li>ID is a UUID string generated by application (not database)</li>
 *   <li>idempotencyKey has UNIQUE constraint to support idempotent payment creation</li>
 *   <li>status is indexed for efficient filtering by state</li>
 *   <li>errorCode and errorMessage are simultaneously set when payment fails</li>
 *   <li>createdAt and updatedAt are always in UTC</li>
 * </ul>
 *
 * <p><b>Immutability Note:</b> This entity provides setters for framework convenience, but business logic
 * should only modify state through dedicated methods like {@code changeStatus()} and {@code markFailed()},
 * not arbitrary field mutations.</p>
 */
@Entity
@Table(name = "payments", indexes = {
        @Index(name = "idx_status", columnList = "status"),
        @Index(name = "idx_idempotency_key", columnList = "idempotency_key", unique = true)
})
public class Payment {

    /**
     * Unique payment identifier (UUID string).
     * Generated by application and persisted as PRIMARY KEY.
     */
    @Id
    @Column(name = "id", length = 36, nullable = false)
    private String id;

    /**
     * Source account from which payment is drawn.
     * Normalized before storage; must not be null and not match destination account.
     */
    @Column(name = "source_account", length = 50, nullable = false)
    private String sourceAccount;

    /**
     * Destination account to which payment is transferred.
     * Normalized before storage; must not be null and must differ from source account.
     */
    @Column(name = "destination_account", length = 50, nullable = false)
    private String destinationAccount;

    /**
     * Payment amount in decimal format.
     * Must be positive, not exceed configured limit (default 1,000,000), and have at most 2 decimal places.
     * Stored as DECIMAL(19,2) for precision; never use double/float.
     */
    @Column(name = "amount", precision = 19, scale = 2, nullable = false)
    private BigDecimal amount;

    /**
     * ISO 4217 currency code (3 characters, uppercase).
     * Validated against supported currency list at creation time.
     * Example: "USD", "EUR", "GBP", "CNY".
     */
    @Column(name = "currency", length = 3, nullable = false)
    private String currency;

    /**
     * Optional reference or description provided by user.
     * Can be null; max 255 characters.
     */
    @Column(name = "reference", length = 255)
    private String reference;

    /**
     * Current payment status in the lifecycle state machine.
     * Values: CREATED, VALIDATED, SENT, COMPLETED, FAILED.
     * Must be updated via {@code changeStatus()} to maintain consistency with audit history.
     */
    @Column(name = "status", length = 20, nullable = false)
    @Enumerated(EnumType.STRING)
    private PaymentStatus status;

    /**
     * Client-provided idempotency key to support retryable payment creation.
     * Must be unique across all payments (UNIQUE constraint in database).
     * Max 100 characters.
     */
    @Column(name = "idempotency_key", length = 100, nullable = false, unique = true)
    private String idempotencyKey;

    /**
     * Stable fingerprint (e.g., SHA256 hash) of request content.
     * Used to distinguish between legitimate replays (same key, same fingerprint)
     * and conflicts (same key, different fingerprint).
     * Max 64 characters; should not be null in practice.
     */
    @Column(name = "request_fingerprint", length = 64, nullable = false)
    private String requestFingerprint;

    /**
     * Error code when payment fails.
     * Only populated when status is FAILED.
     * Examples: "INVALID_AMOUNT", "NETWORK_ERROR", "PROCESSING_ERROR".
     * Must be paired with {@code errorMessage}.
     */
    @Column(name = "error_code", length = 50)
    private String errorCode;

    /**
     * Human-readable error message when payment fails.
     * Only populated when status is FAILED.
     * Must not contain sensitive internal information (e.g., full stack traces).
     */
    @Column(name = "error_message", length = 255)
    private String errorMessage;

    /**
     * Timestamp when payment was created (UTC).
     * Set once at creation and never updated.
     */
    @Column(name = "created_at", nullable = false)
    private Instant createdAt;

    /**
     * Timestamp of last modification (UTC).
     * Updated whenever status or failure details change.
     */
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    // ==================== Constructors ====================

    /**
     * No-argument constructor required by JPA.
     */
    public Payment() {
    }

    /**
     * Full constructor for payment creation.
     *
     * @param id unique identifier
     * @param sourceAccount source account number
     * @param destinationAccount destination account number
     * @param amount payment amount (BigDecimal)
     * @param currency currency code
     * @param reference optional reference text
     * @param status initial status (typically CREATED)
     * @param idempotencyKey idempotency key
     * @param requestFingerprint request fingerprint
     * @param createdAt creation timestamp
     * @param updatedAt last update timestamp
     */
    public Payment(String id, String sourceAccount, String destinationAccount,
                   BigDecimal amount, String currency, String reference,
                   PaymentStatus status, String idempotencyKey, String requestFingerprint,
                   Instant createdAt, Instant updatedAt) {
        this.id = id;
        this.sourceAccount = sourceAccount;
        this.destinationAccount = destinationAccount;
        this.amount = amount;
        this.currency = currency;
        this.reference = reference;
        this.status = status;
        this.idempotencyKey = idempotencyKey;
        this.requestFingerprint = requestFingerprint;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    // ==================== Business Methods ====================

    /**
     * Change payment status to a new state.
     * <b>Precondition:</b> Caller must validate transition via PaymentStateMachine before invoking.
     *
     * @param nextStatus the target status
     * @param changedAt the timestamp of this state change (UTC)
     */
    public void changeStatus(PaymentStatus nextStatus, Instant changedAt) {
        this.status = nextStatus;
        this.updatedAt = changedAt;
    }

    /**
     * Mark payment as FAILED with error details.
     * <b>Precondition:</b> Caller must validate FAILED transition via PaymentStateMachine.
     *
     * @param errorCode the error code (e.g., "NETWORK_ERROR")
     * @param errorMessage the human-readable error message
     * @param changedAt the timestamp of this failure (UTC)
     */
    public void markFailed(String errorCode, String errorMessage, Instant changedAt) {
        this.status = PaymentStatus.FAILED;
        this.errorCode = errorCode;
        this.errorMessage = errorMessage;
        this.updatedAt = changedAt;
    }

    /**
     * Clear error details from a payment (typically when transitioning to success after prior failure).
     * Useful for idempotency: if a payment was previously FAILED but later succeeds,
     * clear the stale error information.
     */
    public void clearFailure() {
        this.errorCode = null;
        this.errorMessage = null;
    }

    // ==================== Getters & Setters ====================

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getSourceAccount() {
        return sourceAccount;
    }

    public void setSourceAccount(String sourceAccount) {
        this.sourceAccount = sourceAccount;
    }

    public String getDestinationAccount() {
        return destinationAccount;
    }

    public void setDestinationAccount(String destinationAccount) {
        this.destinationAccount = destinationAccount;
    }

    public BigDecimal getAmount() {
        return amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    public String getCurrency() {
        return currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }

    public String getReference() {
        return reference;
    }

    public void setReference(String reference) {
        this.reference = reference;
    }

    public PaymentStatus getStatus() {
        return status;
    }

    public void setStatus(PaymentStatus status) {
        this.status = status;
    }

    public String getIdempotencyKey() {
        return idempotencyKey;
    }

    public void setIdempotencyKey(String idempotencyKey) {
        this.idempotencyKey = idempotencyKey;
    }

    public String getRequestFingerprint() {
        return requestFingerprint;
    }

    public void setRequestFingerprint(String requestFingerprint) {
        this.requestFingerprint = requestFingerprint;
    }

    public String getErrorCode() {
        return errorCode;
    }

    public void setErrorCode(String errorCode) {
        this.errorCode = errorCode;
    }

    public String getErrorMessage() {
        return errorMessage;
    }

    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Instant createdAt) {
        this.createdAt = createdAt;
    }

    public Instant getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(Instant updatedAt) {
        this.updatedAt = updatedAt;
    }

    // ==================== Utility Methods ====================

    @Override
    public String toString() {
        return "Payment{" +
                "id='" + id + '\'' +
                ", sourceAccount='" + sourceAccount + '\'' +
                ", destinationAccount='" + destinationAccount + '\'' +
                ", amount=" + amount +
                ", currency='" + currency + '\'' +
                ", status=" + status +
                ", createdAt=" + createdAt +
                ", updatedAt=" + updatedAt +
                '}';
    }
}

